# Generated by Django 3.2 on 2022-08-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sold', 'Выкуп'), ('credit', 'Выкуп не до конца'), ('cancel', 'Расторгнуто'), ('not sold', 'Не продано')], max_length=100)),
                ('area', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('entrance_quantity', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('number_of_apartments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('block', models.ManyToManyField(through='app.Apartment', to='app.Block')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.block'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owners_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
